version: "3.3"

volumes:
    app_data:
        external:
            name: app_data
    app_broker:
        external:
            name: app_broker

services:
    django: &django
        build:
            context: .
            dockerfile: Dockerfile
        image: dockerapp:development
        command: /app/docker/start.sh server
        depends_on:
            - postgres
        env_file:
            - .env
        ports:
            - 8000:8000

    postgres:
        image: postgres:13.3-alpine
        volumes:
            - app_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres

    redis:
        image: redis:6.2.5-alpine
        command: redis-server --appendonly yes
        volumes:
            - app_broker:/var/lib/redis/data

    celery:
        <<: *django
        depends_on:
            - django
            - postgres
            - redis
        ports:
            - 8001:8000
        command: /app/docker/start.sh worker

    beat:
        <<: *django
        depends_on:
            - django
            - postgres
            - redis
        ports:
            - 8002:8000
        command: /app/docker/start.sh beat


    flower:
        <<: *django
        depends_on:
            - celery
            - redis
            - beat
        ports:
        - 5555:5555
        command: /app/docker/start.sh flower

